version: '3'

services:
  chrome:
    image: yukinying/chrome-headless-browser
    cap_add:
      - SYS_ADMIN
    entrypoint: /usr/bin/dumb-init -- /usr/bin/google-chrome-unstable --disable-gpu --headless --disable-dev-shm-usage --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 #--proxy-server=XX.YY.ZZ.TT:8888 --proxy-bypass-list=127.0.0.1 --proxy-bypass-list=0.0.0.0 --user-data-dir=/data --blink-settings=imagesEnabled=false
    ports:
      - "9222:9222"


  mongo:
    image: mvertes/alpine-mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./storage/mongo/db:/data/db


  cassandra:
    #image: cassandra
    build: ./storage/cassandra
    restart: always
    environment:
      # define cluster topology
      - CASSANDRA_CLUSTER_NAME=dfk-db
      - CASSANDRA_DC=dfk-east
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

      # define gossip entrypoints
      #- CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_SEEDS=cassandra 

      # define heap size for local development
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=100M

      # open JMX port for access by Reaper
      # WARNING: this is unsafe in production without proper firewall settings
      - LOCAL_JMX=yes    

    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
    volumes:
      - ./storage/cassandra/db:/var/lib/cassandra
      - ./storage/cassandra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    

  testserver:
    #build: ./testserver
    image: slotix/dfk-testserver
    environment:
      - DFK_TEST=testserver:12345
    ports:
      - "12345:12345"
    depends_on:
      - chrome
    restart: always
  